# Generated by Django 5.0.3 on 2024-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flowers_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
