# Generated by Django 5.0.3 on 2024-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('В сборке', 'В сборке'), ('Передается в доставку', 'Передается в доставку'), ('В пути', 'В пути'), ('На месте', 'На месте'), ('Получен', 'Получен')], max_length=50),
        ),
    ]
