# Generated by Django 5.0.3 on 2024-04-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flowers_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flowers')),
            ],
        ),
    ]
