# Generated by Django 5.0.3 on 2024-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flower_design_greenery_design_packaging_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower_design',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
